version: '{build}'
os: Visual Studio 2015
install:
  - ps: invoke-expression -Command .\ci-install.ps1
build:
  project: build/Build.proj
  verbosity: normal
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: PWCeOQ12fgAhPiBjgkBAqHbvaPQArarsO2sI+8KCeXjBjE+AHaMIMW8b7efmDzQ6
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
